services:
  - type: web
    name: aqar-bot
    env: node
    buildCommand: npm install && npm run install-chrome
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-139.0.7258.138/chrome-linux64/chrome